from characterandenemy import Character
from characterandenemy import Enemy
all_enemies = [
    Enemy(name="Szkielet Orka", 
          health=50, 
          attack=15, 
          defense=5, 
          experience=25, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Gromada szczórów ze wścieklizną", 
          health=70, 
          attack=10, 
          defense=8, 
          experience=30, 
          loot=["Miecz", "Zbroja"]),

    Enemy(name="Król Michał Korybut Wiśniowiecki ", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Legendarny miecz"]),

    Enemy(name="Gruby Goblin ", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Chomik bez łapek ", 
          health=10, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="2 banany", 
          health=100, 
          attack=0, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="2 banany w zbroji", 
          health=100, 
          attack=0, 
          defense=95, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Shrek", 
          health=150, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Legendarny miecz"]),

    Enemy(name="Wiedźma", 
          health=100, 
          attack=26, 
          defense=5, 
          experience=10, 
          loot=["Mikstura leczenia"]),

    Enemy(name="Smok z dziury piekelnej", 
          health=400, 
          attack=62, 
          defense=32, 
          experience=46, 
          loot=["Głowa smoka"]),

    Enemy(name="Biedronka", 
          health=1, 
          attack=10, 
          defense=5, 
          experience=8, 
          loot=["Złoto"]),

    Enemy(name="Biedronka z mieczem", 
          health=1, 
          attack=70, 
          defense=5, 
          experience=10, 
          loot=["Legendarny miecz"]),

    Enemy(name="Kuba z bez oka", 
          health=94, 
          attack=5, 
          defense=20, 
          experience=5, 
          loot=["Złoto"]),

    Enemy(name="Grzegorz wojownik z Dżadary", 
          health=110, 
          attack=90, 
          defense=85, 
          experience=1150, 
          loot=["Legendarny miecz Grzegorza"]),

    Enemy(name="Magiczny kleszcz", 
          health=1, 
          attack=222, 
          defense=0, 
          experience=10, 
          loot=["Złoto"]),

    Enemy(name="Szympans bez nóg", 
          health=10, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Kot QWERTY", 
          health=90, 
          attack=30, 
          defense=95, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Kot kuweta dobrze wiedzieć", 
          health=1, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Golomp Filip", 
          health=190, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Flodin Kitler III", 
          health=300, 
          attack=70, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Wojownik z Zyrutynu", 
          health=120, 
          attack=20, 
          defense=55, 
          experience=90, 
          loot=["Złoto"]),

    Enemy(name="Król Jakub Berk VI", 
          health=300, 
          attack=200, 
          defense=105, 
          experience=5000, 
          loot=["Legendarny komputer Kuby"]),

    Enemy(name="Bandyta", 
          health=300, 
          attack=90, 
          defense=98, 
          experience=110, 
          loot=["Złoto"]),

    Enemy(name="Babcia Dyruna", 
          health=109, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Wacław Bełun ", 
          health=100, 
          attack=70, 
          defense=95, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Wacław Bełun z mieczem oraz zbroją ", 
          health=240, 
          attack=90, 
          defense=65, 
          experience=50, 
          loot=["Legendarny miecz Wacława"]),

    Enemy(name="Chomik bez łapek", 
          health=1, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Cztery złe wróble", 
          health=100, 
          attack=4, 
          defense=55, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Zombie", 
          health=25, 
          attack=70, 
          defense=95, 
          experience=50,  
          loot=["Złoto"]),

    Enemy(name="Dwa Zombie", 
          health=50, 
          attack=70, 
          defense=95, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Trzy Zombie", 
          health=75, 
          attack=70, 
          defense=95, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Cztery Zombie", 
          health=100, 
          attack=70, 
          defense=95, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Opentany wózek", 
          health=100, 
          attack=70, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Ksiądz", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="opętany Ksiądz", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Opętana Zakkonica", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Wózek z złotem i miksturami", 
          health=1, 
          attack=5, 
          defense=0, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Ghull", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Wilk ", 
          health=50, 
          attack=23, 
          defense=45, 
          experience=501, 
          loot=["Mikstura leczenia"]),

    Enemy(name="Trzy Wilki", 
          health=150, 
          attack=23, 
          defense=45, 
          experience=501, 
          loot=["Złoto", "Mikstura leczenia"]),
      
    Enemy(name="Cztery Wilki", 
          health=200, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Wataha Wilków", 
          health=800, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Wilkołak", 
          health=200, 
          attack=40, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Cztery Zmutowane Niedźwiedzie", 
          health=600, 
          attack=80, 
          defense=75, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Wojowniczka Szelbyrg Zarembuna z mieczem", 
          health=100, 
          attack=40, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Czternaście zmutowanych chomików", 
          health=14, 
          attack=28, 
          defense=15, 
          experience=11111111111150, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Pirat Goblin", 
          health=100, 
          attack=250, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Narkoman", 
          health=100, 
          attack=120, 
          defense=115, 
          experience=111150, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Alkocholik", 
          health=103, 
          attack=50, 
          defense=15, 
          experience=5110, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Krasnolód z Baru", 
          health=11100, 
          attack=820, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Czerwony smok", 
          health=1100, 
          attack=110, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),


    Enemy(name="Wojownik", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),


    Enemy(name="Mag", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),


    Enemy(name="Wiedźmin", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="John Wick", 
          health=1100, 
          attack=210, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Jeleń z ujeżdżającym go goblinem", 
          health=1100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Trzy Szkielety", 
          health=100, 
          attack=220, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="P.E.K.A", 
          health=1100, 
          attack=20, 
          defense=135, 
          experience=5330, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="MINI P.E.K.A", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),
      
    Enemy(name="Dartwill II", 
          health=10, 
          attack=210, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Szczór", 
          health=10, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Bober", 
          health=1, 
          attack=60, 
          defense=5, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),


    Enemy(name="Afrykański Pingwin ", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),


    Enemy(name="Grandmaster", 
          health=100, 
          attack=230, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),


    Enemy(name="Ty z przyszlości", 
          health=1100, 
          attack=222220, 
          defense=13335, 
          experience=5013123123123123123123123123123123, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Ty z przeszłości", 
          health=1, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Bandyta z miotaczem ognia ", 
          health=100, 
          attack=220, 
          defense=95, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Karaluch z mieczem", 
          health=1, 
          attack=90, 
          defense=15, 
          experience=510, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Freddy Fazber", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Bonnie", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Foxy", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Król Bratysław Grynys II", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczeniaz"]),

    Enemy(name="Najlepszy informatyk na świecie", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Banan"]),

    Enemy(name="Banan z pistoletami", 
          health=2, 
          attack=90, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Armia małych szkieletów", 
          health=1010, 
          attack=20, 
          defense=115, 
          experience=52222222222220, 
          loot=["Złoto"]),

    Enemy(name="Mag z połamaną laską", 
          health=100, 
          attack=5, 
          defense=5, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Dwaj bandyci", 
          health=200, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),


    Enemy(name="Pedro", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto"]),

    Enemy(name="Zmutowany ziemniak ", 
          health=180, 
          attack=20, 
          defense=15, 
          experience=88, 
          loot=[""]),

    Enemy(name="Szatan", 
          health=6, 
          attack=6, 
          defense=6, 
          experience=666, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Lucyfer", 
          health=6, 
          attack=6, 
          defense=6, 
          experience=666, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Joe zanim został goblinem", 
          health=100, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Las", 
          health= 1011, 
          attack=20, 
          defense=15, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Stanisław najlepszy wojownik na świecie", 
          health= 121, 
          attack=20, 
          defense=55, 
          experience=50, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Tonisław najlepszy wojownik na świecie", 
          health= 111, 
          attack=30, 
          defense=15, 
          experience=550, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Burmistrz Auttuty", 
          health= 101, 
          attack=30, 
          defense=19, 
          experience=550, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Mister Tłister", 
          health= 191, 
          attack=30, 
          defense=15, 
          experience=550, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Bandyta Fender", 
          health= 111, 
          attack=30, 
          defense=15, 
          experience=550, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Poszukiwany Bandyta", 
          health= 111, 
          attack=30, 
          defense=15, 
          experience=550, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Przywódca Bandytów", 
          health= 111, 
          attack=38, 
          defense=45, 
          experience=550, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Kanibal", 
          health= 81, 
          attack=10, 
          defense=1, 
          experience=550, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Berhamin", 
          health= 100, 
          attack=15, 
          defense=15, 
          experience=550, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Zbrodniarz wojenny", 
          health= 250, 
          attack=20, 
          defense=25, 
          experience=650, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Ninja Toshiba", 
          health= 111, 
          attack=30, 
          defense=15, 
          experience=550, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Opętany Traktor", 
          health= 111, 
          attack=30, 
          defense=15, 
          experience=550, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="duch Goblina zwanego Joe", 
          health= 111, 
          attack=35, 
          defense=25, 
          experience=580, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Goblin Ijaedg", 
          health= 251, 
          attack=38, 
          defense=15, 
          experience=559, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Uban Dul Bum Bum (Jaskiniowiec z Dynamitem)", 
          health= 11, 
          attack=200, 
          defense=15, 
          experience=521250, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Wybuchowa owca", 
          health= 11, 
          attack=31230, 
          defense=15, 
          experience=550, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Tajemniczy Bogacz", 
          health= 718, 
          attack= 41, 
          defense= 14, 
          experience= 961, 
          loot=["Złoto", "Mikstura leczenia"]),

    Enemy(name="Jedno oki Goblin zwny Joe", 
          health=40, 
          attack=12, 
          defense=3, 
          experience=20, 
          loot=["Złoto"])]
